name: Install, deploy to PyPI
on:
  push:
    tags: [ "**" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
    - name: Install bmdf
      run: pip install -e .
    - name: Verify README examples are up to date
      run: |
        mdcmd -i README.md
        if git diff --exit-code; then
          echo "README examples are up to date."
        else
          echo "README examples are out of date."
          exit 1
        fi
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install setuptools twine wheel
        python setup.py sdist bdist_wheel
        twine upload dist/*
