name: Test, release
on:
  push:
    branches: [main]
    tags: "v*.*.*"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
    - name: Install bmdf
      run: pip install -e .
    - name: Verify README TOC is up to date
      run: |
        mktoc
        git diff --exit-code
    - name: Verify README examples are up to date
      run: |
        mdcmd
        git diff --exit-code
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install build twine
        python -m build
        twine upload dist/*
