name: Test Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to simulate (e.g., v0.6.2)'
        type: string
        required: true

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v4
    - run: uv python install 3.12
    - name: Create local tag for build
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git tag -a "${{ inputs.tag }}" -m "Test tag for TestPyPI build"
        echo "Created local tag: ${{ inputs.tag }}"
    - name: Build package
      run: uvx --from build pyproject-build --outdir dist
    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        uvx twine upload --verbose --repository testpypi dist/*
        echo "📦 Package published to https://test.pypi.org/project/bmdf/"